AWSTemplateFormatVersion: '2010-09-09'
Description: Cloudwatch alarms

Resources:
  CPUAlarm:
  Type: AWS::CloudWatch::Alarm
  Properties:
    AlarmDescription: CPU alarm for EC2 instance
    AlarmActions:
    - Ref: arn:aws:automate:region:ec2:reboot
    MetricName: CPUUtilization
    Namespace: AWS/EC2
    Statistic: Average
    Period: '60'
    EvaluationPeriods: '3'
    Threshold: '90'
    ComparisonOperator: GreaterThanThreshold
    Dimensions:
    - Name: InstanceId
      Value:
        Ref: EC2